#!/bin/bash
export CHASQUID_CONFIG_FILE=${CHASQUID_CONFIG_FILE:-"/etc/chasquid/chasquid.conf"}
export CSQ_DOMAINS=${CSQ_DOMAINS:-"localhost"} # Multiple values, comma separated
export CSQ_MAX_DATA_SIZE_MB=${CSQ_MAX_DATA_SIZE_MB:-50}
export CSQ_SMTP_ADDRESS=${CSQ_SMTP_ADDRESS:-0.0.0.0:25} # Multiple values, comma separated
export CSQ_SUBMISSION_ADDRESS=${CSQ_SUBMISSION_ADDRESS:-0.0.0.0:587} # Multiple values, comma separated
export CSQ_SUBMISSION_TLS_ADDRESS=${CSQ_SUBMISSION_TLS_ADDRESS:-0.0.0.0:465} # Multiple values, comma separated
export CSQ_MONITORING_ADDRESS=${CSQ_MONITORING_ADDRESS:-127.0.0.1:8080}
export CSQ_MAIL_DELIVERY_AGENT_BIN=${CSQ_MAIL_DELIVERY_AGENT_BIN:-maildrop}
export CSQ_MAIL_DELIVERY_AGENT_ARGS=${CSQ_MAIL_DELIVERY_AGENT_ARGS:--f,%from%,-d,%to_user%}
export CSQ_DATA_DIR=${CSQ_DATA_DIR:-/var/lib/chasquid}
export CSQ_SUFFIX_SEPARATORS=${CSQ_SUFFIX_SEPARATORS:-+}
export CSQ_DROP_CHARACTERS=${CSQ_DROP_CHARACTERS:-.}
export CSQ_MAIL_LOG_PATH=${CSQ_MAIL_LOG_PATH:-<stdout>}
export CSQ_DOVECOT_AUTH=${CSQ_DOVECOT_AUTH:-false}
export CSQ_ARGS=${CSQ_ARGS:-logtime}


# RSPAMD
export RSPAMD_CONNECTION=${RSPAMD_CONNECTION:-rspamd}
export RSPAMD_PASSWORD=${RSPAMD_CONNECTION:-change-me}


# Dovecot Vars
export DOVECOT_DB_HOST=${DOVECOT_DB_HOST:-127.0.0.1}
export DOVECOT_DB_NAME=${DOVECOT_DB_NAME:-mail}
export DOVECOT_DB_USER=${DOVECOT_DB_USER:-dovecot}
export DOVECOT_DB_PASSWORD=${DOVECOT_DB_PASSWORD:-password}

# DKIM
export DKIM_SELECTOR=${DKIM_SELECTOR:-mail}
export DKIM_ALGORITHM=${DKIM_ALGORITHM:-ed25519-sha256}

export DKIM_SECOND_SELECTOR=${DKIM_SECOND_SELECTOR:-mail2}
export DKIM_SECOND_ALGORITHM=${DKIM_SECOND_ALGORITHM:-rsa-sha256}

CHASQUID_CONFIG_DIR="$(dirname "$CHASQUID_CONFIG_FILE")"
export CHASQUID_CONFIG_DIR
